### ISSUE TITLE
puppet version compatibility

### ISSUE THREAD

**Issue by jgrumboe** [rogerlz/puppet-infoblox#1]
Hi,

cool start of a module!
Would like to look deeper into it.
Is this module only puppet 4.x or also puppet 3.x compatible?

greetings,
Jo

**Comment by rogerlz** [comment]
Hi, 

glad that you're interested. 
it should be compatible with puppet 3 as well. If you're having issues let me know and I can help. 

I'll find some time to add more docs this week. :)

cheers, 
Rogerio
